### PR TITLE
feat(readonly-keyword) Add support for parameter properties

### PR DESCRIPTION
**Pull request by ulrichb**
Fixes https://github.com/jonaskello/tslint-immutable/issues/145

### CODE REVIEW

**Comment by RebeccaStevens** [comment]
All looks good to me :)

**Comment by ulrichb** [comment]
Thx for reviewing!

**Comment by ulrichb** [comment]
(Some off topic question) @RebeccaStevens and @jonaskello 

IMO this ESLint test strategy (using inline code; line/column numbers in the expectations; separation between "valid" and "invalid" samples) is much worse than the TSLint ".lint" files approach with inline assertions (sometimes called "gold files"). 

So, is there no equivalent to the TSLint approach? Or did you chose this new strategy on purpose?

I'm asking because I need to port some internal rules too.

**Comment by jonaskello** [comment]
@ulrichb Yes I've been looking for the same thing. I think we discussed it over [here](https://github.com/jonaskello/tslint-immutable/issues/139#issuecomment-497447476) too :-). I have not found any way to test eslint like that in tslint. @RebeccaStevens did most of the port so maybe she knows more.

**Comment by ulrichb** [comment]
Okay. Thx for info.

**Comment by RebeccaStevens** [comment]
As of right now, there is no equivalent in eslint to tslint's .lint files. The tslint team are working with the eslint team to try and make transitioning as easy as possible.

> ESLint’s built-in rule tester is hard to use and the test case syntax is hard to read. We’d like to bring something like TSLint’s testing infrastructure to this project to ensure there are no regressions in the TSLint rule development experience.
> -- https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by ulrichb** [comment]
Thx @RebeccaStevens !

**Pull request merged**
