### PR TITLE
no-conditional-statement

### PR DESCRIPTION
**Pull request by RebeccaStevens**
Replaces no-if-statement

### CODE REVIEW

**Comment by RebeccaStevens** [comment]
@jonaskello I've added an option to ignore conditional statements if each branch contains a return statement. What name do you think we should go with for this option? For now I've named it "allowReturningStatements".

Note: This option only checks the defined branches, not all possible branches. So the following example would not be a violation despite the fact that there is no else return statement (or final return statement for the function).

```ts
const foo = (() => {
  if (condition) {
    return value;
  }
})();
```

Checking all possible branches is possible and I may add that option in future. However, the option would need to (or at least should try to) avoid collision with the [`no-else-return`](https://eslint.org/docs/rules/no-else-return) rule making it a little more difficult to implement. We should probably come up with a name for this option now as well.

**Comment by jonaskello** [comment]
Nice work!

Yes, I can see how `no-else-return` would make it more difficult since then we need to check the whole function. IMO best-practice when using an `if` or `switch` to emulate an expression would be to have all cases fully covered (like in pattern-matching). For `switch` there is the [default-case](https://eslint.org/docs/rules/default-case) rule that requires it to be fully covered by a default case. I guess the equivalent for `if` would be a rule that requires `else` to be present but it seems there is no such rule.

One way to go would be to not do the fully covered checking in `no-conditional-statment` but instead delegate that to the `default-case` rule for `switch` and for `if` implement an equivalent new rule that requires an `else` part to be present. However, if you emulate conditional expressions by putting if-statments in separate functions you might want to have the return at the end instead of an `else` so not sure what is best here. My feeling right now is that having an `else` required is the best option since it keeps the `if` statement self-contained and so it is easier to see it as an expression. Looking at the [do-expressions](https://github.com/tc39/proposal-do-expressions) proposal they have an example with `if` which uses `else`, but I don't think that would be required, it would probably allow any expression at the end outside of the if statement instead of an else branch.

**Comment by jonaskello** [comment]
Regarding the option name, perhaps something like `ignoreReturn` or `allowReturn`? Or perhaps `allowReturningBranches` to be more explicit. I haven't checked the code but I guess with this option the error reporting could be per-branch?

**Comment by RebeccaStevens** [comment]
I've renamed the option to `allowReturningBranches`. It can now be set either to a boolean or to "onlyIfExhaustive". All branches must be defined if "onlyIfExhaustive" is specified (if statements require else statements, switch statements require default cases).

I've asked a [question over at microsoft/TypeScript](https://github.com/microsoft/TypeScript/issues/32415) to see if it is possible to check for exhaustive switches that don't have a default case.

Other than that, I think this PR is ready.

**Comment by jonaskello** [comment]
Perhaps `allowReturningBranches: "onlyIfExhaustive"` could be shortened to `allowReturningBranches: "ifExhaustive"` without loosing any clarity?

Other than that I think this is good to go :-).

**Pull request merged**
